### ISSUE TITLE
Methods for creating accounts and applications

### ISSUE THREAD

**Issue by mayorova** [3scale/3scale-api-ruby#14]
A common use case for the support team is batch importing of user accounts and API keys (i.e. applications) and further updates.
For being able to use the client in Ruby scripts these methods for the following endpoints are required:
- Signup Express
- Application Create

Other endpoints necessary for further manipulation of the imported data:
- Application List
- Application Read
- Application Update

**Comment by mikz** [comment]
Actually I forgot the Application Update.
