### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by sgutierr** [3scale/3scale-api-ruby#35]
There are some file modifications made them after coming out release 0.1.5 therefore it isn't able to get  the last content of this repo when some is installing for instance the 3scale-toolbox. 
Perform a sync of bump version maybe tagging in a new release 0.1.6 would be fixed.   

Thanks

**Comment by mikz** [comment]
You can clone/download the repository and run:

```shell
gem build 3scale-api.gemspec
gem install 3scale-api-*.gem
```

To build & install the latest version. Also PRs to improve readme with these instructions and clarifications what is released.
Also you can see what is not released in the [CHANGELOG.md](https://github.com/3scale/3scale-api-ruby/blob/b6d4b09b9f9353a7c31043f826db039bc8a8664e/CHANGELOG.md#unreleased).
